
name: Deploy Backend to AWS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  ECR_REPO: lx-fta-backend
  ECS_CLUSTER: lx-fta-cluster
  AUTH_SECRET_NAME: lx-fta-auth-secrets
  SECRETSMANAGER_SECRET_ARN: arn:aws:secretsmanager:us-east-1:263307268672:secret:lx-fta-auth-secrets-gTBwYG

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Configure AWS credentials for deployment
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.DEPLOYMENT_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Generate image tag
        id: tag
        run: echo "TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and tag Docker image
        run: |
          docker build -t $ECR_REPO:${{ env.TAG }} backend/

      - name: Push Docker image to ECR
        run: |
          docker tag $ECR_REPO:${{ env.TAG }} ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/$ECR_REPO:${{ env.TAG }}
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/$ECR_REPO:${{ env.TAG }}

      - name: Deploy with Terraform
        run: |
          if [ -d infrastructure ]; then
            cd infrastructure
            terraform init
            terraform apply -auto-approve \
              -var="image_tag=${{ env.TAG }}" \
              -var="auth_secret_name=${{ env.AUTH_SECRET_NAME }}" \
              -var="secretsmanager_secret_arn=${{ env.SECRETSMANAGER_SECRET_ARN }}"
          else
            echo "❌ 'infrastructure/' directory not found. Deployment aborted."
            exit 1
          fi
