name: Deploy Backend to AWS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  ECR_REPO: lx-fta-backend
  ECS_CLUSTER: lx-fta-cluster
  
permissions:
  id-token: write        # Required for OIDC authentication
  contents: read         # Allows GitHub to checkout the code

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Configure AWS credentials for deployment
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.DEPLOYMENT_ROLE_ARN }} # IAM role with ECR/Terraform permissions
          aws-region: ${{ env.AWS_REGION }}

      - name: Generate image tag
        id: tag
        run: echo "TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and tag Docker image
        run: |
          docker build -t $ECR_REPO:${{ env.TAG }} backend/
          docker tag $ECR_REPO:${{ env.TAG }} ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/$ECR_REPO:${{ env.TAG }}

      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/$ECR_REPO:${{ env.TAG }}

      - name: Set Terraform variables
        run: |
          echo "TF_VAR_image_tag=${{ env.TAG }}" >> $GITHUB_ENV
          echo "TF_VAR_acm_cert_arn=${{ secrets.ACM_CERT_ARN }}" >> $GITHUB_ENV
          echo "TF_VAR_aws_account_id=${{ secrets.AWS_ACCOUNT_ID }}" >> $GITHUB_ENV
          echo "TF_VAR_aws_region=${{ env.AWS_REGION }}" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init
        working-directory: infrastructure/terraform/backend

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: infrastructure/terraform/backend
